package br.com.uarini.pogapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "POKEMON".
 */
@Entity
public class Pokemon {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Integer number;
    private Integer image;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Pokemon() {
    }

    public Pokemon(Long id) {
        this.id = id;
    }

    @Generated
    public Pokemon(Long id, String name, Integer number, Integer image) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.image = image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getImage() {
        return image;
    }

    public void setImage(Integer image) {
        this.image = image;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
