package br.com.uarini.pogapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "POKEMON_DATA".
 */
@Entity
public class PokemonData {

    @Id(autoincrement = true)
    private Long id;
    private Integer qtd;

    @Property(nameInDb = "qtd_candy")
    private Integer qtdCandy;

    @Property(nameInDb = "qtd_candy_evolve")
    private Integer qtdCandyEvolve;
    private Integer transfer;

    @Property(nameInDb = "pokemon_number")
    private Integer pokemonNumber;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PokemonData() {
    }

    public PokemonData(Long id) {
        this.id = id;
    }

    @Generated
    public PokemonData(Long id, Integer qtd, Integer qtdCandy, Integer qtdCandyEvolve, Integer transfer, Integer pokemonNumber) {
        this.id = id;
        this.qtd = qtd;
        this.qtdCandy = qtdCandy;
        this.qtdCandyEvolve = qtdCandyEvolve;
        this.transfer = transfer;
        this.pokemonNumber = pokemonNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQtd() {
        return qtd;
    }

    public void setQtd(Integer qtd) {
        this.qtd = qtd;
    }

    public Integer getQtdCandy() {
        return qtdCandy;
    }

    public void setQtdCandy(Integer qtdCandy) {
        this.qtdCandy = qtdCandy;
    }

    public Integer getQtdCandyEvolve() {
        return qtdCandyEvolve;
    }

    public void setQtdCandyEvolve(Integer qtdCandyEvolve) {
        this.qtdCandyEvolve = qtdCandyEvolve;
    }

    public Integer getTransfer() {
        return transfer;
    }

    public void setTransfer(Integer transfer) {
        this.transfer = transfer;
    }

    public Integer getPokemonNumber() {
        return pokemonNumber;
    }

    public void setPokemonNumber(Integer pokemonNumber) {
        this.pokemonNumber = pokemonNumber;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
